#!/bin/bash
#SBATCH --job-name=1B-gidd-fineweb-8gpu-2node-jsc-a100-8bs-fsdp2-gas
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=4
#SBATCH --cpus-per-task=48
#SBATCH --time=01:00:00
#SBATCH --account=laionize
#SBATCH --partition=develbooster
#SBATCH --output=/p/project/laionize/vettoruzzo1_juwelsbooster/gidd/slurm_logs/%x-%j.out
#SBATCH --error=/p/project/laionize/vettoruzzo1_juwelsbooster/gidd/slurm_logs/%x-%j.err

# For quick tests on max 4 nodes, max 2h walltime and internet connection: #SBATCH --partition=develbooster
# For more nodes and time: set #SBATCH --partition=booster

set -e  # Exit immediately on error

# Activate environment
module purge #module Stages/2025 remains loaded by default. If you want to unload it use `module --force purge`
module load GCCcore/.13.3.0 Python/3.12.3 NCCL/default-CUDA-12
export VENV_PATH="/p/project/laionize/vettoruzzo1_juwelsbooster/gidd/.venv"
source $VENV_PATH/bin/activate


#---- Config ----
MODEL=gidd                                  # Options: gidd, ar
MODEL_SIZE=1B                               # Options: 1B, small, base, tiny
DATASET=fineweb                             # Options: fineweb
MBS=8                                       # Micro batch size. Opions: 4, 8, 16, 32
SL=512                                      # Sequence length. Options: 512, 1024, 4096
GBS=                                        # Global batch size. Based on this, #GPUs, MBS, # grad acc steps are automatically set
TRAIN_STEPS=1000                            # Training steps. Default=1000
FSDP=False                                  # FSDP. Options: True, False
FSDP_SHARDING=SHARD_GRAD_OP                 # Sharding strategy (if FSDP). Option: FULL_SHARD, SHARD_GRAD_OP

if [ "$MODEL_SIZE" == "small" ]; then
    N_PARAMS="0.17"
elif [ "$MODEL_SIZE" == "base" ]; then
    N_PARAMS="0.42"
elif [ "$MODEL_SIZE" == "1B" ]; then
    N_PARAMS="1.50"
else
    echo "Unknown MODEL_SIZE: $MODEL_SIZE"
    exit 1
fi

SL_NAME=""
GBS_NAME=""
FSDP_NAME="" # Initialize FSDP_NAME to an empty string
if [ -n "$SL" ]; then
    SL_NAME="-${SL}sl"
fi
if [ -n "$GBS" ]; then
    GBS_NAME="-${GBS}gbs"
fi
if [ "$FSDP" == "True" ]; then
    if [ "$FSDP_SHARDING" == "SHARD_GRAD_OP" ]; then
        FSDP_NAME="-fsdp2"
    elif [ "$FSDP_SHARDING" == "FULL_SHARD" ]; then
        FSDP_NAME="-fsdp3"
    fi
fi


#---- Set directories----
curr_file="$(scontrol show job "$SLURM_JOB_ID" | grep '^[[:space:]]*Command=' | head -n 1 | cut -d '=' -f 2-)"
curr_dir="$(dirname "$curr_file")"
# Add outer 'gidd/' directory to PYTHONPATH so imports like 'from gidd.models...' work
export PYTHONPATH="/p/project1/laionize/vettoruzzo1_juwelsbooster/gidd:$PYTHONPATH" 
export WDIR="/p/project/laionize/vettoruzzo1_juwelsbooster/gidd/gidd_logs"


#---- Distributed training----
export MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
# Allow communication over InfiniBand cells.
# adding “i” to hostname is crucial, otherwise compute nodes will not be able to communicate
export MASTER_ADDR="$MASTER_ADDR"i
export MASTER_PORT=54123
# Prevent NCCL not figuring out how to initialize.
export NCCL_SOCKET_IFNAME=ib0
# Prevent Gloo not being able to communicate.
export GLOO_SOCKET_IFNAME=ib0

NODE_COUNT=$(scontrol show hostnames $SLURM_JOB_NODELIST | wc -l)
TOTAL_GPUS=$((SLURM_NNODES * SLURM_GPUS_PER_NODE))
DISTRIBUTED_ARGS=(
    --nproc-per-node $SLURM_GPUS_PER_NODE 
    --nnodes $SLURM_NNODES
)
# Make all GPUs on the nodes visible
export CUDA_VISIBLE_DEVICES=0,1,2,3

# to run wandb in offline mode
export WANDB_MODE=offline


#---- Print in job file ----
echo "Job submission date: $(date)"
echo "Number of nodes allocated: $NODE_COUNT"
echo "Number of GPUs allocated: $TOTAL_GPUS"
echo "MASTER_ADDR: $MASTER_ADDR"
echo "Running on node: $(hostname)"
echo "Current file: $curr_file"
echo "Current directory: $curr_dir"
echo "Python path: $PYTHONPATH"

JOB_NAME="JSC-${SLURM_JOB_ID}-${N_PARAMS}B-${TOTAL_GPUS}gpu-${MBS}mbs-${DATASET}-${MODEL}${SL_NAME}${GAS_NAME}${FSDP_NAME}"
echo "Run saved with job name $JOB_NAME"


#---- Launch training ----
cd /p/project/laionize/vettoruzzo1_juwelsbooster/gidd

srun env -u CUDA_VISIBLE_DEVICES torchrun_jsc "${DISTRIBUTED_ARGS[@]}" \
  --rdzv_id=$SLURM_JOBID \
  --rdzv_backend=c10d \
  --rdzv_endpoint=$MASTER_ADDR:$MASTER_PORT \
  --master_addr=$MASTER_ADDR \
  --master_port=$MASTER_PORT \
  -m gidd.train \
    --config-name=$MODEL \
    data.dataset_name=/p/home/jusers/vettoruzzo1/juwels/vettoruzzo1_juwelsbooster/datasets/FineWeb10BT \
    data.tokenizer_name=gpt2 \
    data.cache_dir=/p/scratch/laionize/vettoruzzo1/.cache \
    model=$MODEL_SIZE \
    model.max_seq_len=$SL \
    training.global_train_batch_size=$GBS \
    training.train_batch_size=$MBS \
    training.eval_batch_size=$MBS \
    training.num_train_steps=$TRAIN_STEPS \
    training.fsdp=$FSDP \
    training.fsdp_sharding_strategy=$FSDP_SHARDING \
    logging.wandb_project=gidd-gidd \
    logging.run_name="$JOB_NAME" \
    hydra.job.name="$JOB_NAME"