run_name: null
num_eval_batches: 128
log_freq: 10
eval_freq: 2000
save_freq: 2000
save_dir: /leonardo_scratch/large/userexternal/avettoru/checkpoints
wandb_entity: oellm-team
wandb_project: gidd-mdlm
